# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    - echo "Before script section"
# Install necessary tools
    - apt-get update && apt-get install -y
    - apt-get install net-tools -y
    - apt update -y
    - apt-get install xdotool  -y
    - apt install unzip

# Install Java
    - apt install default-jre -y
    - apt-get install wget -y

# Install the NSS tools to configure SSL
    - apt-get install libnss3-tools
    - mkdir -p $HOME/.pki/nssdb
    - apt-get install vim -y

# Install Firefox
    - apt install firefox -y

# Install Apache Ant
    - apt install ant -y

# Install Graphicsmagick
    - apt-get install graphicsmagick -y

# Install Chrome
    - apt-get install libxss1 libappindicator1 libindicator7 -y
ARG CHROME_VERSION="91.0.4472.114-1"
    - wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb
    - dpkg -i google-chrome*.deb; exit 0
    - apt-get install -f -y
    - dpkg -i google-chrome*.deb

# Install Sahi
    - mkdir sahi_pro
    - cd /sahi_pro
    - wget https://resources.sahipro.com/installers/pro/install_sahi_pro_v970_20220511.jar
    - echo '<AutomatedInstallation langpack="eng">\n\
<com.izforge.izpack.panels.HelloPanel/>\n\
<com.izforge.izpack.panels.HTMLInfoPanel/>\n\
<com.izforge.izpack.panels.HTMLInfoPanel/>\n\
<com.izforge.izpack.panels.LicencePanel/>\n\
<com.izforge.izpack.panels.TargetPanel>\n\
<installpath>sahi_pro_970</installpath>\n\
</com.izforge.izpack.panels.TargetPanel>\n\
<com.izforge.izpack.panels.PacksPanel>\n\
	<pack name="Sahi Core" index="0" selected="true"/>\n\
	<pack name="Tools" index="1" selected="true"/>\n\
	<pack name="Sample Java Project" index="2" selected="true"/>\n\
	<pack name="Editor support files" index="3" selected="true"/>\n\
</com.izforge.izpack.panels.PacksPanel>\n\
<com.izforge.izpack.panels.InstallPanel/>\n\
<com.izforge.izpack.panels.ShortcutPanel/>\n\
<com.izforge.izpack.panels.ProcessPanel/>\n\
<com.izforge.izpack.panels.FinishPanel/>\n\
</AutomatedInstallation>' > silent_install.xml
    - java -jar install_sahi_pro_v970_20220511.jar silent_install.xml

# Install fixes for chromeHL screenshot
    - wget https://chromedriver.storage.googleapis.com/91.0.4472.101/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - wget https://resources.sahipro.com/fixes/ChromeHL_SC_v901_Patch.zip
    - unzip ChromeHL_SC_v901_Patch.zip
    - cp -R BROWSER/* /sahi_pro/sahi_pro_970/
    - cp -R chromedriver /sahi_pro/sahi_pro_970/ext/headless/chrome/
    - chmod -R 777 /sahi_pro/sahi_pro_970/ext/headless/

# Configure browser for Sahi
    - cd /sahi_pro/sahi_pro_970/userdata/config
    - echo '<browserTypes>\n\
	<browserType>\n\
		<name>chromeHL</name>\n\
		<displayName>ChromeHL</displayName>\n\
		<icon>chrome.png</icon>\n\
		<path>$sahiDir/ext/headless/chrome/chromeHL_launch.sh</path>\n\
		<options>"-path /usr/bin/google-chrome" --user-data-dir=$userDir/browser/chrome/profiles/sahi$threadNo --proxy-server=$browserProxyHost:$browserProxyPort  --incognito --headless --disable-gpu --no-sandbox</options>\n\
		<processName>chrome</processName>\n\
		<capacity>5</capacity>\n\
	</browserType>\n\
\n\
	<browserType>\n\
		<name>firefoxHL</name>\n\
		<displayName>firefoxHL</displayName>\n\
		<icon>firefox.png</icon>\n\
		<path>/usr/bin/firefox</path>\n\
		<options>-profile "$userDir/browser/ff/profiles/sahi$threadNo" -no-remote -headless</options>\n\
		<processName>firefox</processName>\n\
		<capacity>5</capacity>\n\
	</browserType>\n\
</browserTypes>' > browser_types.xml

# Add product key (Specify your product key within quotes in the line below)
    - echo '45634ef607391041e70a3db0b28dd0fb961b' > productkey.txt

    - cd..
    - cd bin/
    - nohup ./start_sahi.sh &
    - sleep 30

    - chmod -R -f 777 ../certgen

    - sh ./add_ssl_root_cert_linux.sh
    - sh ./verify_ssl_root_cert_linux.sh
    - sh ./stop_sahi.sh
    - sleep 10
    - nohup ./start_sahi.sh &
    - sleep 30


    - sh ./testrunner.sh  demo/clickCombo.sah http://sahitest.com/demo/ chromeHL
#    - ant -f ../../build.xml

    - echo "========================================================================================"
    - pwd
    - ls
    - echo "========================================================================================"

  displayName: 'Run a multi-line script'
